<?php

$finder = PhpCsFixer\Finder::create()
    ->in(["spec", "src"])
;

return PhpCsFixer\Config::create()
    ->setRules([
        "@PSR1" => true,
        "@PSR2" => true,
        "blank_line_after_opening_tag" => true,
        "array_syntax" => ["syntax" => "short"],
        "align_multiline_comment" => true,
        "binary_operator_spaces" => true,
        "blank_line_before_statement" => ["statements" => ['throw', 'return', 'try']],
        "cast_spaces" => ["space" => "none"],
        "class_attributes_separation" => ["elements" => ["method"]],
        "combine_consecutive_issets" => true,
        "combine_consecutive_unsets" => true,
        "compact_nullable_typehint" => true,
        "concat_space" => ["spacing" => "one"],
        "escape_implicit_backslashes" => true,
        "explicit_string_variable" => true,
        "function_typehint_space" => true,
        "include" => true,
        "linebreak_after_opening_tag" => true,
        "list_syntax" => ["syntax" => "short"],
        "magic_constant_casing" => true,
        "multiline_comment_opening_closing" => true,
        "multiline_whitespace_before_semicolons" => true,
        "native_function_casing" => true,
        "new_with_braces" => true,
        "no_empty_comment" => true,
        "no_empty_phpdoc" => true,
        "no_empty_statement" => true,
        "no_extra_blank_lines" => true,
        "no_leading_import_slash" => true,
        "no_leading_namespace_whitespace" => true,
        "no_mixed_echo_print" => ["use" => "echo"],
        "no_multiline_whitespace_around_double_arrow" => true,
        "multiline_whitespace_before_semicolons" => true,
        "no_short_bool_cast" => true,
        "no_spaces_around_offset" => true,
        "no_spaces_inside_parenthesis" => true,
        "no_superfluous_elseif" => true,
        "no_trailing_comma_in_singleline_array" => true,
        "no_trailing_whitespace" => true,
        "no_trailing_whitespace_in_comment" => true,
        "no_unneeded_final_method" => true,
        "no_unused_imports" => true,
        "no_useless_else" => true,
        "no_useless_return" => true,
        "no_whitespace_before_comma_in_array" => true,
        "no_whitespace_in_blank_line" => true,
        "normalize_index_brace" => true,
        "object_operator_without_whitespace" => true,
        "ordered_class_elements" => true,
        "ordered_imports" => true,
        "phpdoc_add_missing_param_annotation" => ["only_untyped" => false],
        "phpdoc_align" => true,
        "phpdoc_annotation_without_dot" => true,
        "phpdoc_no_empty_return" => true,
        "phpdoc_no_useless_inheritdoc" => true,
        "phpdoc_order" => true,
        "phpdoc_scalar" => true,
        "phpdoc_summary" => true,
        "phpdoc_trim" => true,
        "phpdoc_types" => true,
        "return_type_declaration" => true,
        "semicolon_after_instruction" => true,
        "short_scalar_cast" => true,
        "single_blank_line_before_namespace" => true,
        "single_line_comment_style" => true,
        "single_quote" => true,
        "standardize_not_equals" => true,
        "ternary_operator_spaces" => true,
        "trailing_comma_in_multiline_array" => true,
        "trim_array_spaces" => true,
        "whitespace_after_comma_in_array" => true,
        "yoda_style" => ["equal" => false, "identical" => false, "less_and_greater" => false],

        "no_trailing_comma_in_list_call" => true,
        "no_null_property_initialization" => true,
        "no_break_comment" => ["comment_text" => "Fallthrough intentional..."],
        "class_keyword_remove" => false,
    ])
    ->setFinder($finder)
;