version: '2.1'
services:
  package:
    image: drupsys/phpspec-package
    container_name: system-logger
    volumes:
      - ./:/package:cached
      - vendor:/package/vendor:cached

  coverage:
    image: drupsys/phpspec-coverage
    container_name: system-logger-coverage
    volumes:
    - ./src:/code/src:cached
    - ./spec:/code/spec:cached
    - ./phpspec.yml:/code/phpspec.yml
    - vendor:/code/vendor:cached
    - coverage:/usr/share/nginx/html:cached
    ports:
    - "8101:80"
    environment:
      CLASS_COVERAGE_MAX: 100
      CLASS_COVERAGE_MIN: 80
      METHOD_COVERAGE_MAX: 100
      METHOD_COVERAGE_MIN: 80
      LINE_COVERAGE_MAX: 100
      LINE_COVERAGE_MIN: 80

  metrics:
    image: drupsys/phpmetrics
    container_name: system-logger-metrics
    volumes:
    - ./src:/code/src:cached
    - metrics:/usr/share/nginx/html:cached
    ports:
    - "8102:80"

volumes:
  vendor:
  metrics:
  coverage:
