version: '2.1'
services:
  package:
    image: drupsys/package
    container_name: system-logger
    volumes:
    - ./:/package:cached
    - ./vendor:/package/vendor:cached

  tests:
    image: drupsys/phpspec
    container_name: system-logger-tests
    volumes:
    - ./src:/code/src:cached
    - ./spec:/code/spec:cached
    - ./phpspec.yml:/code/phpspec.yml
    - ./vendor:/code/vendor:cached

  coverage:
    image: drupsys/phpspec-coverage
    container_name: system-logger-coverage
    volumes:
    - ./src:/code/src:cached
    - ./spec:/code/spec:cached
    - ./phpspec.yml:/code/phpspec.yml
    - ./vendor:/code/vendor:cached
    - coverage:/usr/share/nginx/html:cached
    ports:
    - "8101:80"
    environment:
      CLASS_COVERAGE_MAX: 100
      CLASS_COVERAGE_MIN: 80
      METHOD_COVERAGE_MAX: 100
      METHOD_COVERAGE_MIN: 80
      LINE_COVERAGE_MAX: 100
      LINE_COVERAGE_MIN: 80

  linter:
    image: drupsys/php-linter
    container_name: system-logger-linter
    volumes:
    - ./src:/code/src:cached
    - ./spec:/code/spec:cached
    - ./linter/php_cs.php:/code/.php_cs.dist:cached
    - ./linter/mvf_ruleset.xml:/code/mvf_ruleset.xml:cached

  metrics:
    image: drupsys/phpmetrics
    container_name: system-logger-metrics
    volumes:
    - ./src:/code/src:cached
    - metrics:/usr/share/nginx/html:cached
    ports:
    - "8102:80"

volumes:
  metrics:
  coverage:
