version: '2.1'
services:
  package:
    image: drupsys/phpspec-package
    container_name: system-logger
    volumes:
      - ./:/package:cached
    environment:
      CLASS_COVERAGE_MAX: 100
      CLASS_COVERAGE_MIN: 80
      METHOD_COVERAGE_MAX: 100
      METHOD_COVERAGE_MIN: 80
      LINE_COVERAGE_MAX: 100
      LINE_COVERAGE_MIN: 80

  metrics:
    image: drupsys/phpmetrics
    container_name: system-logger-metrics
    volumes:
    - ./src:/code/src:cached
    - metrics:/usr/share/nginx/html:cached
    ports:
    - "8100:80"

volumes:
  metrics:
