version: '2.1'
services:
  package:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: system-logger
    volumes:
      - ./:/package:cached

  metrics:
    image: drupsys/phpmetrics
    container_name: system-logger-metrics
    volumes:
    - ./src:/code/src:cached
    - metrics:/usr/share/nginx/html:cached
    ports:
    - "8100:80"

volumes:
  metrics:
